spring:
  application:
    # 应用名称
    name: zh_tools
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
  main:
    log-startup-info: false
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    servlet:
      #Content-Type 的值（默认值： text/html ）
      content-type: text/html
    # 开启模板缓存（默认值： true ）
    cache: false
    # 模板编码
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    time-zone: GMT+8
logging:
  pattern:
    #设置日志等级
    #    level: INFO
    #设置输出日期格式
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    rolling-file-name: log/%d{yyyy-MM-dd}日志_%i.log
  file:
    path: log
    max-size: 10MB
    max-history: 50
    total-size-cap: 10GB
server:
  servlet:
    encoding:
      charset: UTF-8
  error:
    include-stacktrace: always
  tomcat:
    accept-count: 500
    threads:
      max: 500
    max-connections: 10000
